# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scratchRLHF',
                'doc_host': 'https://suchith720.github.io',
                'git_url': 'https://github.com/suchith720/scratchRLHF',
                'lib_path': 'scratchRLHF'},
  'syms': {'scratchRLHF.core': {'scratchRLHF.core.foo': ('core.html#foo', 'scratchRLHF/core.py')}}}
